CREATE DATABASE Q2
USE Q2

-- CREATE TABLE: NHACC
CREATE TABLE NHACC(
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC NVARCHAR(100),
    DiaChi NVARCHAR(200),
    DienThoai VARCHAR(15)
);

-- CREATE TABLE: DONDH
CREATE TABLE DONDH(
    SoDH VARCHAR(10) PRIMARY KEY,
    NgayDH DATE,
    MaNCC VARCHAR(10),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);


-- CREATE TABLE: PNHAP
CREATE TABLE PNHAP(
    SoPN VARCHAR(10) PRIMARY KEY,
    NgayNhap DATE,
    SoDH VARCHAR(10),
    FOREIGN KEY(SoDH) REFERENCES DONDH(SoDH)
);

-- CREATE TABLE: VATTU
CREATE TABLE VATTU(
    MaVT VARCHAR(10) PRIMARY KEY,
    TenVT NVARCHAR(100),
    DVT NVARCHAR(50),
    PhanTram DECIMAL(5,2)
);

-- CREATE TABLE: CTPNHAP
CREATE TABLE CTPNHAP(
    SoPN VARCHAR(10),
    MaVT VARCHAR(10),
    SLNhap INT,
    DGNhap DECIMAL(15,2),
    PRIMARY KEY(SoPN, MaVT),
    FOREIGN KEY(SoPN) REFERENCES PNHAP(SoPN),
    FOREIGN KEY(MaVT) REFERENCES VATTU(MaVT)
);

-- CREATE TABLE: CTDONDH
CREATE TABLE CTDONDH(
    SoDH VARCHAR(10),
    MaVT VARCHAR(10),
    SLDat INT,
    PRIMARY KEY(SoDH, MaVT),
    FOREIGN KEY(SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaVT) REFERENCES VATTU(MaVT)
);

-- CREATE TBALE: TONKHO
CREATE TABLE TONKHO(
    NamThang VARCHAR(6),
    MaVT VARCHAR(10),
    SLDau INT,
    TongSLN INT,
    TongSLX INT,
    SLCuoi INT,
    PRIMARY KEY(NamThang, MaVT),
    FOREIGN KEY (MaVT) REFERENCES VATTU(MaVT)
);

-- CREATE TABLE: PXUAT
CREATE TABLE PXUAT(
    SoPX VARCHAR(10) PRIMARY KEY,
    NgayXuat DATE,
    TenKH NVARCHAR(100)
);

-- CREATE TABLE: CTPXUAT
CREATE TABLE CTPXUAT (
    SoPX VARCHAR(10),
    MaVT VARCHAR(10),
    SLXuat INT,
    DGXuat DECIMAL(15,2),
    PRIMARY KEY(SoPX, MaVT),
    FOREIGN KEY(MaVT) REFERENCES VATTU(MaVT)
);