/*
CREATE DATABASE Q1_DE3_SU23
USE Q1_DE3_SU23
*/
CREATE TABLE Departments(
	DepID VARCHAR(10),
	DepName NVARCHAR(50),
	DepDescription NVARCHAR(200),

	PRIMARY KEY(DepID)
)

CREATE TABLE Lectures(
	LecID VARCHAR(10),
	FristName NVARCHAR(30),
	LastName NVARCHAR(30),
	LecDate DATE,
	DepID VARCHAR(10),

	PRIMARY KEY(LecID),
	FOREIGN KEY(DepID) REFERENCES Departments(DepID)
)

CREATE TABLE Subjects(
	SubID VARCHAR(10),
	SubName NVARCHAR(30),
	NumberOfPersons INT,
	SubDescription NVARCHAR(200),

	PRIMARY KEY(SubID)
)

CREATE TABLE Lecture(
	LecID VARCHAR(10),
	SubID VARCHAR(10),
	S1 NVARCHAR(30),
	S2 NVARCHAR(30),

	PRIMARY KEY(LecID, SubID),
	FOREIGN KEY(LecID) REFERENCES Lectures(LecID),
	FOREIGN KEY(SubID) REFERENCES Subjects(SubID)

)