--=====STORE PROCEDURE=====
--1. VIET THU TUC HIEN THI DS DU AN GOM: MADA, TENDA, SO SO NV, TONG SO GIO
CREATE PROC USP_DS_THONG_KE_DU_AN_CAU1
AS
BEGIN
	SELECT P.proNum, P.proName,
		COUNT(O.empSSN) AS N'SỐ NV THAM GIA',
		SUM(O.workHours) AS N'TỔNG SỐ GIỜ'
	FROM tblProject P, tblWorksOn O
	WHERE P.proNum=O.proNum
	GROUP BY P.proNum, P.proName
END
--TEST
EXEC USP_DS_THONG_KE_DU_AN_CAU1

--2. VIET THU TUC HIEN THI DS DU AN VOI MA DA DUOC CHI DINH GOM: MADA, TENDA, SO SO NV, TONG SO GIO
CREATE PROC USP_DS_THONG_KE_DU_AN_CAU2
	@MADA INT
AS
BEGIN
	SELECT P.proNum, P.proName, 
		COUNT(O.empSSN) AS N'SỐ NV THAM GIA',
		SUM(O.workHours) AS N'TỔNG SỐ GIỜ'
	FROM tblProject P, tblWorksOn O
	WHERE P.proNum=O.proNum AND P.proNum=@MADA
	GROUP BY P.proNum, P.proName
END
--TEST
EXEC USP_DS_THONG_KE_DU_AN_CAU2 2
EXEC USP_DS_THONG_KE_DU_AN_CAU2 @MADA=3

--3. VIET THU TUC HIEN THI DS DU AN VOI MA DA DUOC CHI DINH GOM: MADA, TENDA, SO SO NV, TONG SO GIO, TEN PHONG QL
CREATE PROC USP_DS_THONG_KE_DA_CAU3
	@MADA INT
AS
BEGIN
	SELECT P.proNum, P.proName,
	COUNT(O.empSSN) AS N'SỐ NV THAM GIA',
	SUM(O.workHours) AS N'TỔNG SỐ GIỜ',
	D.depName
	FROM tblProject P, tblWorksOn O, tblDepartment D
	WHERE P.proNum=O.proNum AND P.depNum=D.depNum AND P.proNum=@MADA
	GROUP BY P.proNum, P.proName, D.depName
END
--TEST
EXEC USP_DS_THONG_KE_DA_CAU3 4

--4. VIET THU TUC HIEN THI DS DU AN VOI MA DA DUOC CHI DINH GOM: MADA, TENDA, SO SO NV NAM, SO NV NU
CREATE PROC USP_DS_THONG_KE_DA_CAU4
	@MADA INT
AS
BEGIN
	SELECT P.proNum, P.proName,
		SUM(CASE WHEN E.empSex='M' THEN 1 ELSE 0 END) AS N'SỐ NV NAM',
		SUM(CASE WHEN E.empSex='F' THEN 1 ELSE 0 END) AS N'SỐ NV NỮ'
	FROM tblProject P, tblWorksOn O, tblEmployee E
	WHERE P.proNUM=O.proNum AND O.empSSN=E.empSSN AND P.proNum=@MADA
	GROUP BY P.proNum, P.proName
END
--TEST
EXEC USP_DS_THONG_KE_DA_CAU4 3

--=====FUNCTION=====
--5 VIET HAM TINH TONG LUONG CUA NHAN VIEN
CREATE FUNCTION FN_TINH_TONG_LUONG_NV_CAU5()
RETURNS DECIMAL(10, 0)
AS
BEGIN
	DECLARE @TONGLUONG AS DECIMAL(10, 0)
	SELECT @TONGLUONG=SUM(E.empSalary)
	FROM tblEmployee E
	RETURN @TONGLUONG
END
--TEST
SELECT DBO.FN_TINH_TONG_LUONG_NV_CAU5() --C1
PRINT N'TỔNG LƯƠNG NV LÀ: ' + CAST(DBO.FN_TINH_TONG_LUONG_NV_CAU5() AS NVARCHAR) --C2

--6 VIET HAM TINH TONG LUONG CUA NHAN VIEN THUOC PHONG CO MA DUOC CHI DINH
ALTER FUNCTION FN_TINH_TONG_LUONG_NV_CAU6(@MAPHONG AS INT)
RETURNS INT
AS 
BEGIN
	DECLARE @TONGLUONG AS INT
	SELECT @TONGLUONG=SUM(E.empSalary)
	FROM tblEmployee E
	WHERE E.depNum=@MAPHONG
	RETURN @TONGLUONG
END
--TEST
SELECT DBO.FN_TINH_TONG_LUONG_NV_CAU6(1)

--7. VIET HAM CHO BIET SO NGUOI THAM GIA VAO DU AN CO MADA DUOC CHI DINH
--FN_SO_NGUOI_THAM_GIA_DU_AN_CHI_DINH_CAU7
ALTER FUNCTION FN_SO_NGUOI_THAM_GIA_DU_AN_CHI_DINH_CAU7(@MADA AS INT)
RETURNS INT
AS
BEGIN

	DECLARE @TONGTHGIA AS INT
	SELECT @TONGTHGIA=COUNT(O.empSSN)
	FROM tblWorksOn O
	WHERE O.proNum=@MADA
	RETURN @TONGTHGIA

	--RETURN (SELECT COUNT(o.empSSN) FROM tblWorksOn O WHERE O.proNum=@MADA)
END
--TEST
SELECT DBO.FN_SO_NGUOI_THAM_GIA_DU_AN_CHI_DINH_CAU7(1)

--8 VIẾT HÀM TRẢ VỀ BẢNG GỒM DS NHÂN VIÊN THUỘC PHÒNG CÓ MÃ PHÒNG ĐƯỢC CHỈ ĐỊNH
--GỒM: MÃ PHÒNG, TÊN PHÒNG, MÃ NHÂN VIÊN, TÊN NHÂN VIÊN, LƯƠNG
ALTER FUNCTION FN_DSNV_THEO_PHONG_CAU8(@MAPHONG AS INT)
RETURNS TABLE
AS
RETURN (SELECT E.empName, E.empSalary, D.depName
		FROM tblDepartment D, tblEmployee E
		WHERE D.depNum=E.depNum AND D.depNum=@MAPHONG)
--TEST
SELECT * FROM DBO.FN_DSNV_THEO_PHONG_CAU8(1)

--9. VIẾT HÀM TRẢ VỀ BẢNG THỐNG KÊ DS NHÂN VIÊN 
--GỒM: MÃ PHÒNG, TÊN PHÒNG, LƯƠNG THẤP NHẤT, LƯƠNG CAO NHẤT, SỐ NV NAM, SỐ NV NỮ
CREATE FUNCTION FN_CAU9()
RETURNS @RES TABLE(
	MAPHONG INT,
	TENPHONG NVARCHAR(50),
	LUONG_THAP_NHAT DECIMAL(10, 0),
	LUONG_CAO_NHAT DECIMAL(10, 0),
	SONV_NAM INT,
	SONV_NU INT
)
AS
BEGIN
	INSERT INTO @RES
		SELECT D.depNum, D.depName, MIN(E.empSalary), MAX(E.empSalary),
			SUM(CASE WHEN E.empSex='M' THEN 1 ELSE 0 END),
			SUM(CASE WHEN E.empSex='F' THEN 1 ELSE 0 END)
		FROM tblDepartment D, tblEmployee E
		WHERE D.depNum=E.depNum
		GROUP BY D.depNum, D.depName
		RETURN;
END
--TEST
SELECT * FROM DBO.FN_CAU9()

